### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by elkhalifte** [valsap/cordova-plugin-applovinmax-ads#1]
Thanks for the plugin.
Is there any example!
I dont know what should I do with YOUR_PLACEMENT_TO_REWARD_AT_SERVER_SIDE

**Comment by valsap** [comment]
Hi, elkhalifte!
If you wanna reward user at server side (S2S), you can put your placement to this field. Then, you can separate rewards by placements at server. It's best approach to secure you reward processes. 

If you reward user at client side and don't use S2S, just ignore this field.

**Comment by elkhalifte** [comment]
Thank You. 👍 🥇
